In [57]:
import numpy as np

In [18]:
zero = np.zeros(6)

In [19]:
zero

array([0., 0., 0., 0., 0., 0.])

In [20]:
zero.dtype

dtype('float64')

In [21]:
one = np.ones(10)

In [22]:
one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
one.dtype

dtype('float64')

In [24]:
# for identity matrix we can also use 'eye' function
identity = np.identity(4)

In [25]:
identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
zeros_uint32 = np.zeros(8, dtype="u4")
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

In [33]:
l = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [34]:
l

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
l[1,1]=24

In [37]:
l

array([[ 1,  2,  3],
       [ 4, 24,  6],
       [ 7,  8,  9]])

In [30]:
l.shape

(3, 3)

In [23]:
myarr1 = np.array([[[1,2],[4,5],[4,5]],[[7,9],[5,6],[10,11]]])
# myarr1 = np.array([[1,2,3],[4,5,6]])

In [24]:
myarr1

array([[[ 1,  2],
        [ 4,  5],
        [ 4,  5]],

       [[ 7,  9],
        [ 5,  6],
        [10, 11]]])

In [26]:
myarr1.shape

(2, 3, 2)

In [3]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])

In [4]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [29]:
arr.T

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [6]:
np.dot(arr,arr.T)

array([[ 1,  2,  3,  0,  0],
       [ 2,  9,  8,  1, -1],
       [ 3,  8, 49, -8,  8],
       [ 0,  1, -8,  2, -2],
       [ 0, -1,  8, -2,  2]])

In [7]:
np.dot(arr.T,arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [13]:
arr.T @ arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [23]:
arr.swapaxes(0, 1)

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [21]:
arr

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [63]:
bools = np.array([False, False, True, False])
bools.dtype

dtype('bool')